#!/bin/sh

cd $HOME
ln -s dotfiles/.bashrc .
ln -s .bashrc .bash_profile
ln -s dotfiles/.tmux.conf .

mkdir .bashrc.d
ln -s dotfiles/less .bashrc.d/

# vim configuration

ln -s dotfiles/.vimrc .
cp dotfiles/.vimrc.local .

ln -s dotfiles/.ctags .

mkdir .vim
cd .vim

ln -s ../dotfiles/.vim/vimstall .
./vimstall base
