#!/bin/sh

configure_vim() {
	ln -s dotfiles/.vimrc
	cp dotfiles/.vimrc.local

	ln -s dotfiles/.ctags

	mkdir .vim
	cd .vim

	ln -s ../dotfiles/.vim/vimstall
	./vimstall base
}

configure_bash() {
	ln -s dotfiles/.bashrc
	ln -s .bashrc .bash_profile
	ln -s dotfiles/.tmux.conf

	mkdir .bashrc.d
	for default in less history editor; do
		ln -s "../dotfiles/.bashrc.d/$default" .bashrc.d/
	done
}

main () {
	cd $HOME

	configure_bash
	configure_vim
}

main()
