#!/bin/sh

usage() {
	echo "$0 [base|pathogen|colors|update|vim-sensible|vim-editorconfig|vim-sync|vim-go|vim-go-explorer|vim-php-cs-fixer]"
	exit 1
}

#$1 plugin name
plugin_repo() {
	# NOTE: remember to update usage ^^

	case "$1" in
	# language-agnostic
	vim-sensible)     echo "git://github.com/tpope/vim-sensible.git" ;;
	vim-editorconfig) echo "https://github.com/editorconfig/editorconfig-vim" ;;
	vim-sync)         echo "https://github.com/eshion/vim-sync" ;;
	vim-tagbar)       echo "https://github.com/majutsushi/tagbar" ;;
	# language-specific
	vim-go)           echo "https://github.com/fatih/vim-go.git" ;;
	vim-go-explorer)  echo "https://github.com/garyburd/go-explorer" ;;
	vim-php-cs-fixer) echo "https://github.com/stephpy/vim-php-cs-fixer" ;;
	*) return 1 ;;
	esac

	return 0
}

#$1 plugin name
plugin_dir() {
	case "$1" in
	# have to be special!
	vim-editorconfig) echo "editorconfig-vim" ;;
	vim-go-explorer)  echo "go-explorer" ;;
	vim-tagbar)       echo "tagbar" ;;
	*)                echo "$1" ;;
	esac

	return 0
}

pathogen_install() {
	if [ ! -d bundle ]; then
		echo "Pathogen not found, installing?"
		$0 pathogen
	fi

	cd bundle
}


case "$1" in
pathogen)
	# https://github.com/tpope/vim-pathogen
	for d in autoload bundle; do
		if [ ! -e $d ]; then
			mkdir $d;
		fi
	done

	curl -SsLo autoload/pathogen.vim https://tpo.pe/pathogen.vim
	;;
vim-*)
	pathogen_install

	DIR="$(plugin_dir "$1")"
	if [ -d "$DIR" ]; then
		(
			cd "$DIR"
			git pull
		)
	else
		REPO="$(plugin_repo "$1")"
		if ! [ -z "$REPO" ]; then
			git clone "$REPO"
		else
			echo "Could not find a repo matching $1"
			usage
		fi
	fi
	;;
update)
	if [ -d "autoload" ]; then
		echo "Updating pathogen..."
		$0 "pathogen";
	fi

	if [ -d "colors"  ]; then
		echo "Updating colors..."
		$0 "colors";
	fi

	if [ -d "bundle" ]; then
		for b in bundle/*; do
			echo "Updating $b..."
			(cd $b; git pull)
		done
	fi
	;;
colors)
	if [ ! -e "colors" ]; then
		mkdir colors
	fi

	(
		cd colors

		# https://github.com/tomasr/molokai
		curl -SsOJ "https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim"

		# https://github.com/noahfrederick/vim-noctu
		curl -SsOJ "https://raw.githubusercontent.com/noahfrederick/vim-noctu/master/colors/noctu.vim"
	)
	;;
base)
	$0 pathogen
	$0 colors
	$0 vim-sensible
	;;
wipe)
	rm -rf autoload
	rm -rf bundle
	rm -rf colors
	;;
*)
	usage
	;;
esac
