#!/bin/sh

_dotfiles_goenv() {
	GOROOT="$HOME/go"
	if [ ! -d "$GOROOT" ]; then
		return 0
	fi

	export GOROOT

	if [ -d "$HOME/Documents/go" ]; then
		export GOPATH="$HOME/Documents/go"
	else
		export GOPATH="$HOME/dev/go"
	fi

	export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
}

_dotfiles_goenv "$@"
