#!/bin/sh

# adapted from: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases
_dotfiles_ssh_agent_load_env() {
	local env="$1"

	if [ -f "$env" ]; then
		. "$env" > /dev/null
	fi
}

_dotfiles_ssh_agent_start() {
	local env="$1"

	(
		umask 077
		ssh-agent > "$env"
	)
	. "$env" > /dev/null
}

_dotfiles_ssh_agent() {
	local env="$HOME/.ssh/agent.env"
	local agent_run_state="2"

	_dotfiles_ssh_agent_load_env "$env"

	# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2=agent not running
	agent_run_state="$(ssh-add -l > /dev/null 2>&1; echo $?)"

	if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
	    _dotfiles_ssh_agent_start "$env"
	    ssh-add
	elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
	    ssh-add
	fi
}

_dotfiles_ssh_agent "$@"
